### PR TITLE
Use custom styles

### PR DESCRIPTION
**Pull request by rojvv**
- [x] Hero
- [x] Cards
- [x] Footer
- [x] Interactive light-dark mode (based on user settings and toggling with double click)
- [x] Search with name
- [x] Search with tags
- [x] Mind previous performance PRs
- [x] Remove `@import` rules wherever possible as [not recommended by Sass](https://sass-lang.com/documentation/at-rules/import)

### CODE REVIEW

**Comment by rojvv** [comment]
About the previous commit: `next/image` won't work in this case, because it can't get styled as we want.

**Comment by AramRafeq** [comment]
@roj1512  this looks amazing keep it up

**Comment by rojvv** [comment]
@AramRafeq thank you very much for the support!

**Comment by mhmd-azeez** [comment]
Looks very good but I do prefer keeping the "Join the list" and "Contribute" buttons as is

**Comment by rojvv** [comment]
@mhmd-azeez one question, were you the one who implemented BubbleUI? Because I get the element type is invalid error when using it.

**Comment by rojvv** [comment]
> Looks very good but I do prefer keeping the "Join the list" and "Contribute" buttons as is

Done.

**Comment by mhmd-azeez** [comment]
@roj1512 I didn't do the Bubble UI thing. I only did the initial api stuff

**Comment by hezhamen** [comment]
Dast xosh @roj1512 ... BubbleUI @AramRafeq krdi

**Comment by rojvv** [comment]
<div align="right">
کاک @hezhamen، ناتوانم بەبڵیوای هاوردە بکەم. تۆ پێشتر چۆن کردووتە؟
</div>

**Comment by hezhamen** [comment]
ڕاستییەکەی ئارام کردوویەتی، بەڵام نەمانتوانیوە بە جوانی بەکاریبهێنین لە لۆکەڵ و لە ڕیمۆتەکەمان فەرقی هەیە ستایلەکەی.

**Comment by rojvv** [comment]
من ئەمەم ڕووبەڕوو دەبێتەوە:
image

**Comment by hezhamen** [comment]
Can you show us the relevant code?

**Comment by rojvv** [comment]
هەر ئەم دێڕەیە:
```ts
import BubbleUI from "bubble-ui-react";
```

@hezhamen

**Comment by hezhamen** [comment]
Remove the package, we won't be using it in our next design.

**Comment by rojvv** [comment]
YAY!

**Comment by AramRafeq** [comment]
Delete the Buble UI it has issues, one note on the mobile I would prefer less margin  the if the cards were wider it would be easier to user
Screenshot_2021-12-29-16-03-48-15_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by rojvv** [comment]
@AramRafeq try now :)

**Comment by AramRafeq** [comment]
@roj1512 I can't see the change however I will merge this let's do it later

**Pull request merged**
