### PR TITLE
Tons of improvements

### PR DESCRIPTION
**Pull request by rojvv**
* Much much better README parsing
* Rewrite in TypeScript
* Use Yarn <3
* No longer use the unsafe pages/api
* Better `key=`s
* Other optimizations & improvements

### CODE REVIEW

**Comment by hezhamen** [comment]
We have to wait for @AramRafeq to tell us where the build went wrong.

**Comment by rojvv** [comment]
@hezhamen I fixed everything, waiting for your approval to get this merged :)

**Comment by AramRafeq** [comment]
image

**Comment by rojvv** [comment]
@AramRafeq it's fixed.

**Comment by AramRafeq** [comment]
@roj1512  it is not working properly  i will add contribution guidelines please follow that for future PRs
image

**Comment by rojvv** [comment]
I'm fixing that, sorry.

**Comment by AramRafeq** [comment]
@roj1512 sorry the changes are to major i will close this each PR should be atomic and only add/fix one thing if a PR contains more than that separate them into smaller parts this way it will be more manageable

**Comment by rojvv** [comment]
Aright!

**Pull request closed without merging**
